//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucTap_DuAnTeam_PhamThiVi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGVIECTUAN
    {
        public int idCongViecTuan { get; set; }
        public Nullable<int> idTuan { get; set; }
        public Nullable<int> idNguoiDung { get; set; }
        public Nullable<int> idModule { get; set; }
        public string TenIssue { get; set; }
        public string Urllssue { get; set; }
        public string TenCongViec { get; set; }
        public Nullable<int> ThoiGianLam { get; set; }
        public string Nguon { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public string GhiChu { get; set; }
    
        public virtual MODULE MODULE { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual TUANLAMVIEC TUANLAMVIEC { get; set; }
    }
}
