//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucTap_DuAnTeam_PhamThiVi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGNHANSUTHEOTHANG
    {
        public int idDanhGiaNSThang { get; set; }
        public Nullable<int> idThang { get; set; }
        public Nullable<int> idNguoiDung { get; set; }
        public string KhoiLuong { get; set; }
        public string ChatLuong { get; set; }
        public string TienDo { get; set; }
        public string XepLoai { get; set; }
        public string NhanXetCaThang { get; set; }
        public Nullable<int> TBThang { get; set; }
        public Nullable<int> TongGio { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual THANGLAMVIEC THANGLAMVIEC { get; set; }
    }
}
