//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucTap_DuAnTeam_PhamThiVi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANGLAMVIEC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THANGLAMVIEC()
        {
            this.DGNHANSUTHEOTHANGs = new HashSet<DGNHANSUTHEOTHANG>();
            this.TUANLAMVIECs = new HashSet<TUANLAMVIEC>();
        }
    
        public int idThang { get; set; }
        public Nullable<int> idDuAn { get; set; }
        public Nullable<int> GiaTri { get; set; }
        public Nullable<int> Nam { get; set; }
        public string TenThang { get; set; }
        public Nullable<System.DateTime> NgayBDLam { get; set; }
        public Nullable<System.DateTime> NgayKTLam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DGNHANSUTHEOTHANG> DGNHANSUTHEOTHANGs { get; set; }
        public virtual DUAN DUAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TUANLAMVIEC> TUANLAMVIECs { get; set; }
    }
}
