//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucTap_DuAnTeam_PhamThiVi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUANLAMVIEC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUANLAMVIEC()
        {
            this.CONGVIECTUANs = new HashSet<CONGVIECTUAN>();
            this.DGNHANSUTHEOTUANs = new HashSet<DGNHANSUTHEOTUAN>();
        }
    
        public int idTuan { get; set; }
        public Nullable<int> idThang { get; set; }
        public Nullable<int> STTTuan { get; set; }
        public string TenTuan { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public Nullable<int> SoGioLamViec { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONGVIECTUAN> CONGVIECTUANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DGNHANSUTHEOTUAN> DGNHANSUTHEOTUANs { get; set; }
        public virtual THANGLAMVIEC THANGLAMVIEC { get; set; }
    }
}
